rootProject.name = "moamoa"

include("moamoa-core")
include("moamoa-core:core-api")
include("moamoa-core:core-batch")
include("moamoa-crawler")

include("moamoa-infra")
include("moamoa-infra:cache-api")
include("moamoa-infra:cache-redis")
include("moamoa-infra:cache-caffeine")
include("moamoa-infra:cache-resilient")
include("moamoa-infra:cache-redis-starter")
include("moamoa-infra:cache-caffeine-starter")
include("moamoa-infra:cache-resilient-starter")
include("moamoa-infra:queue-api")
include("moamoa-infra:queue-redis")
include("moamoa-infra:queue-redis-starter")
include("moamoa-infra:set-api")
include("moamoa-infra:set-redis")
include("moamoa-infra:set-redis-starter")
include("moamoa-infra:lock-api")
include("moamoa-infra:lock-redisson")
include("moamoa-infra:lock-local")
include("moamoa-infra:lock-resilient")
include("moamoa-infra:lock-redisson-starter")
include("moamoa-infra:lock-resilient-starter")
include("moamoa-infra:messaging-api")
include("moamoa-infra:messaging-redis")
include("moamoa-infra:messaging-redis-starter")
include("moamoa-infra:token-api")
include("moamoa-infra:token-jwt")
include("moamoa-infra:token-jwt-starter")
include("moamoa-infra:password-api")
include("moamoa-infra:password-crypto")
include("moamoa-infra:password-crypto-starter")
include("moamoa-infra:mail-api")
include("moamoa-infra:mail-mailgun")
include("moamoa-infra:mail-mailgun-starter")

include("moamoa-support")
include("moamoa-support:support-api-docs")
include("moamoa-support:support-templates")
include("moamoa-support:support-monitoring")
include("moamoa-support:support-webhook")
include("moamoa-support:support-logging")
include("moamoa-support:support-test")

include("moamoa-admin")
include("moamoa-admin:admin-api")
include("moamoa-admin:admin-web")

include("moamoa-web")
