admin:
  datasource:
    enabled: ${ADMIN_DB_ENABLED:false}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${LOG_DB_SCHEMA}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 5
    minimum-idle: 1
    connection-timeout-ms: 3000
    idle-timeout-ms: 600000
    max-lifetime-ms: 600000
