spring:
  r2dbc:
    url: r2dbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?useServerPrepareStatement=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

batch:
  run-key: ${BATCH_RUN_KEY}

logging:
  level:
    io.micrometer.prometheus.PrometheusMeterRegistry: ERROR
    io.micrometer.prometheusmetrics.PrometheusMeterRegistry: ERROR
